config/routes.rb
Zpin::Application.routes.draw do
  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  get "/contact", to: "pages#contact", as: "contact"
  post "/emailconfirmation", to: "pages#email", as: "email_confirmation"
  
  get "pins", to: "pins#index", as: "pins"
  post "pins/create"
  get "pins/pins"
  post "pins/favourite"
      
  devise_for :users
  
  namespace :admin do
    root "base#index"
    resources :users    
  end
  
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
	belongs_to :user
	belongs_to :pin
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	has_attached_file :pin, :styles => {:medium => "300x300"}
	validates_attachment_content_type :pin, :content_type => /\Aimage\/.*\Z/

	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pins
  has_many :favourites
  # Use friendly_id on Users
  extend FriendlyId
  friendly_id :friendify, use: :slugged
  
  # necessary to override friendly_id reserved words
  def friendify
    if username.downcase == "admin"
      "user-#{username}"
    else
      "#{username}"
    end
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  # Pagination
  paginates_per 100
  
  # Validations
  # :username
  validates :username, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /\A[a-zA-Z0-9]*\z/, on: :create, message: "can only contain letters and digits"
  validates :username, length: { in: 4..10 }
  # :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  
  def self.paged(page_number)
    order(admin: :desc, username: :asc).page page_number
  end
  
  def self.search_and_order(search, page_number)
    if search
      where("username LIKE ?", "%#{search.downcase}%").order(
      admin: :desc, username: :asc
      ).page page_number
    else
      order(admin: :desc, username: :asc).page page_number
    end
  end
  
  def self.last_signups(count)
    order(created_at: :desc).limit(count).select("id","username","slug","created_at")
  end
  
  def self.last_signins(count)
    order(last_sign_in_at: 
    :desc).limit(count).select("id","username","slug","last_sign_in_at")
  end
  
  def self.users_count
    where("admin = ? AND locked = ?",false,false).count
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :require_admin!
  
  def index
    @last_signups = User.last_signups(10)
    @last_signins = User.last_signins(10)
    @count = User.users_count 
    
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [
    :show,
    :edit,
    :update,
    :destroy
  ]
  

  def index
    @users = User.search_and_order(params[:search], params[:page])
  end
  
  def show
    redirect_to edit_admin_user_path(params[:id])
  end
  
  def edit
  end
  
  def update
    old_username = @user.username
    new_params = user_params.dup
    new_params[:username] = new_params[:username].strip
    new_params[:email] = new_params[:email].strip
    
    @user.username = new_params[:username]
    @user.email = new_params[:email]
    @user.password = new_params[:password] if new_params[:password].strip.length > 0
    @user.password_confirmation = new_params[:password_confirmation] if new_params[:password_confirmation].strip.length > 0
    
    if current_user.id != @user.id
      @user.admin = new_params[:admin]=="0" ? false : true
      @user.locked = new_params[:locked]=="0" ? false : true
    end
    
    if @user.valid?
      @user.skip_reconfirmation!
      @user.save
      redirect_to admin_users_path, notice: "#{@user.username} updated."
    else
      flash[:alert] = "#{old_username} couldn't be updated."
      render :edit
    end
  end
  
  
  private 
  
  def set_user
    @user = User.friendly.find(params[:id])
  rescue
    flash[:alert] = "The user with an id of #{params[:id]} doesn't exist."
    redirect_to admin_users_path
  end
  
  def user_params
    params.require(:user).permit(
    :username,
    :email,
    :password,
    :password_confirmation,
    :admin,
    :locked
    )
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :reject_locked!, if: :devise_controller?
  

  # Devise permitted params
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(
      :username, 
      :email, 
      :password, 
      :password_confirmation) 
    }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(
      :username, 
      :email, 
      :password, 
      :password_confirmation,
      :current_password
      ) 
    }
  end
  
  # Redirects on successful sign in
  def after_sign_in_path_for(resource)
    inside_path
  end
  
  # Auto-sign out locked users
  def reject_locked!
    if current_user && current_user.locked?
      sign_out current_user
      user_session = nil
      current_user = nil
      flash[:alert] = "Your account is locked."
      flash[:notice] = nil
      redirect_to root_url
    end
  end
  helper_method :reject_locked!
  
  # Only permits admin users
  def require_admin!
    authenticate_user!
    
    if current_user && !current_user.admin?
      redirect_to root_path
    end
  end
  helper_method :require_admin!
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [
    :inside
  ]

  def home
  end
  
  def inside
    @pins = current_user.pins
  end
   
  
  def email
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    
    if @name.blank?
      flash[:alert] = "Please enter your name before sending your message. Thank you."
      render :contact
    elsif @email.blank? || @email.scan(/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i).size < 1
      flash[:alert] = "You must provide a valid email address before sending your message. Thank you."
      render :contact
    elsif @message.blank? || @message.length < 10
      flash[:alert] = "Your message is empty. Requires at least 10 characters. Nothing to send."
      render :contact
    elsif @message.scan(/<a href=/).size > 0 || @message.scan(/\[url=/).size > 0 || @message.scan(/\[link=/).size > 0 || @message.scan(/http:\/\//).size > 0
      flash[:alert] = "You can't send links. Thank you for your understanding."
      render :contact
    else    
      ContactMailer.contact_message(@name,@email,@message).deliver
      redirect_to root_path, notice: "Your message was sent. Thank you."
    end
  end
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	def index
	end

	def create
		pin = Pin.new
		pin.name = params[:name]
		pin.description = params[:description]
		pin.pin = params[:pin]
		pin.user = current_user
		if pin.save
			flash[:notice] = "Successfully added a pin."
			redirect_to action: :index
		else
			flash[:error] = pin.full_error_messages.join(',')
			redirect_to inside_path
		end
	end

	def pins
		user_fav = current_user.favourites.collect{ |f| f.pin_id }
		pins = []
		Pin.all.each do |pin|
			p = {}
			p[:id] = pin.id
			p[:name] = pin.name
			p[:description] = pin.description
			p[:url] = pin.pin.url
			p[:murl] = pin.pin.url(:medium)
			p[:favourite] = user_fav.include?(pin.id)
			p[:owner] = (current_user.id == pin.user_id)
			pins << p
		end
		respond_to do |format|
			format.json { render :json => pins }
		end
	end

	def favourite
		if params[:make] == "fav"
			fav = Favourite.new
			fav.user = current_user
			fav.pin = Pin.find params[:id]
			if fav.save
				respond_to do |format|
					format.json { render :json => "Success"}
				end
			end
		elsif params[:make] == "unfav"
			fav = current_user.favourites.where(pin_id: params[:id]).first
			if fav.destroy
				respond_to do |format|
					format.json { render :json => "Success"}
				end
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(value)
    unless value.nil?
      @title = "#{value} | Zpin"      
    end
  end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/admin/base/index.html.erb
<% title("Admin") %>
<h1>Admin <small>Home</small></h1>
<div class="row">
  <div class="col-sm-4">
    <h3>Menu</h3>
    <h4><%= link_to "Users", admin_users_path %> <small>- <%= "#{pluralize(@count, 'user')}" %></small></h4>
    
    <hr/>
  </div>
  
  <div class="col-sm-4">
    <h3>Last Sign Ups</h3>
    <ul class="list-unstyled">
      <% @last_signups.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.username, edit_admin_user_path(user) %><br/>
        <small><%= time_ago_in_words(user.created_at)%> ago</small>
      </li>
      <% end %>
    </ul>
  </div>
  
  <div class="col-sm-4">
    <h3>Last Sign Ins</h3>
    <ul class="list-unstyled">
      <% @last_signins.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.username, edit_admin_user_path(user) %><br/>
        <small>
          <% unless user.last_sign_in_at.nil? %>
          <%= time_ago_in_words(user.last_sign_in_at)%> ago
          <% else %>
          never
          <% end %>
        </small>
      </li>
      <% end %>
    </ul>
  </div>
  
</div>

app/views/admin/users/edit.html.erb
<% title("Edit User Id: #{@user.id}") %>
<div class="row">
  <div class="col-sm-6">
    <h1>
      Edit User <small><%= "#{@user.username.capitalize} - id: #{@user.id}" %></small>
    </h1>
    <p><%= link_to "Back to Users", admin_users_path %></p>

    <%= form_for [:admin, @user], :html => { :role => "form" } do |f| %>
    
    <div class="form-group">
      <%= f.label :username %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_field :username, :autofocus => true, class: "form-control" %>  
        </div>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :email %>
      <div class="row">
        <div class="col-sm-6">      
          <%= f.email_field :email, class: "form-control" %>  
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
    </div>
    
    <% unless current_user.id == @user.id %>
		<div class="form-group">
			<div class="row">
				<div class="col-sm-6">
      		<%= f.check_box :locked %> <%= f.label :locked, "Is Locked?" %>
				</div>
			</div>
		</div>
    
		<div class="form-group">
			<div class="row">
				<div class="col-sm-6">			
      		<%= f.check_box :admin %> <%= f.label :admin, "Is Admin?" %>
				</div>
			</div>
		</div> 
    <% end %>

    <div class="row">
      <div class="col-sm-6">
        <%= f.submit "Update User", class: "btn btn-danger" %>
      </div>
    </div>    
    
    <% end %>

  </div>
</div>

app/views/admin/users/index.html.erb
<% title("Users Admin") %>
<h1>Users <small>Admin</small></h1>
<p><%= link_to "Back to Admin", admin_root_path %></p>

<div class="text-center">
  <p><%= page_entries_info @users %></p>
  <%= paginate @users %>
</div>

<%= form_tag admin_users_path, method: 'get', html: {role: "form"} do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
    <%= link_to "All", admin_users_path, {class: "btn btn-sm btn-link"} %>
  </p>
<% end %>

<table class="table table-striped">
  <tr>
    <th>User ID</th>
    <th>Username</th>
    <th>Admin</th>
    <th>Locked</th>
    <th>Email</th>
    <th>Sign In Count</th>
    <th>Created At</th>
    <th>Last Sign In</th>
    <th>Last Sign In IP</th>
  </tr>
  
  <% @users.each do |user| %>
  
  <tr>
    <td><%= user.id %></td>
    <td><%= link_to user.username.capitalize, admin_user_path(user) %></td>
    <td><%= user.admin? ? "<b>yes</b>".html_safe : "no" %></td>
    <td><%= user.locked? ? "<b>yes</b>".html_safe : "no" %></td>
    <td><%= user.email %></td>
    <td><%= user.sign_in_count %></td>
    <td><%= time_ago_in_words(user.created_at) %></td>
    <% unless user.last_sign_in_at.nil? %>
    <td><%= time_ago_in_words(user.last_sign_in_at)%> ago</td>
    <% else %>
    <td>never</td>
    <% end %>
    <td><%= user.last_sign_in_ip %></td>
  </tr>
  
  <% end %>
  
</table>

<div class="text-center">
  <p><%= page_entries_info @users %></p>
  <%= paginate @users %>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    
    <div class="row footer-first-row">
      
      <div class="col-xs-12 text-center">
        <p><small>
          &copy; 2014 - Yourself!
          <br/>
          Assembled with <%= link_to "RailsBricks", "http://www.railsbricks.net" %>
        </small></p>
      </div>
      
    </div>
    
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to "Contact", contact_path %></li>
<% if !user_signed_in? %>
<li><%= link_to "Sign in", new_user_session_path %></li>
<li><%= link_to "Sign up", new_user_registration_path %></li>
<% else %>
<li><%= link_to "User Home", inside_path %></li>
<li><%= link_to "All Pins", pins_path %></li>
<li><%= link_to "Edit your account", edit_user_registration_path %></li>

<% if current_user.admin? %>
<li><%= link_to "Admin", admin_root_path %></li>
<% end %>

<li><%= link_to "Sign out", destroy_user_session_path, data:{method: :delete} %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "Zpin" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application", controller_name %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
      
    <div class="container">
       
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>     
      </div>  
      
    </div>
  </div>
    
  <%= render 'layouts/footer' %>    

</body>
</html>

app/views/pages/contact.html.erb
<% title("Contact") %>
<h1 class="page-title">Contact</h1>

<div class="row">
  <div class="col-sm-6">
    
    <%= form_tag email_confirmation_path, method: 'post', html: {role: "form"} do %>
    
    <div class="form-group">
      <%= label_tag :name, "Your name" %>
      <div class="row">
        <div class="col-xs-12">
          <%= text_field_tag :name, @name, placeholder: "Enter your name...", :autofocus => true, class: "form-control" %>  
        </div>
      </div>
    </div>
    
    <div class="form-group">
      <%= label_tag :email, "Your email" %>
      <div class="row">
        <div class="col-xs-12">
          <%= text_field_tag :email, @email, placeholder: "Enter your email...", class: "form-control" %>  
        </div>
      </div>
    </div>
    
    <div class="form-group">
      <%= label_tag :message, "Your message" %>
      <div class="row">
        <div class="col-xs-12">
          <%= text_area_tag :message, @message, placeholder: "Enter your message...", rows: 10, class: "form-control" %>  
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-xs-12 padded">
        <button class='btn btn-primary'>
          <i class='fa fa-envelope'></i> Send
        </button>
      </div>
    </div>
    <% end %>
      
  </div>
</div>

app/views/pages/home.html.erb
<% title("Home Page") %>
<h1><i class="fa fa-home"></i> Home Page </h1>
<p>Pinterest like App for ZANEC interview</p>
<h4>Login details</h4>
<p>Username : admin, user1, user2,......,user50</p>
<p>Password for test accounts: 1234</p>

app/views/pages/inside.html.erb
<% title("New Pin") %>
<h2>Welcome</h2>
<h4>Add New Pin</h4>
<%= form_tag(url_for({action: "create", controller: "pins"}), multipart: true) do %>
	<div class="form-group">
		<label>Name</label>
		<%= text_field_tag :name, params[:name], placeholder: "Name", required: true, class: "form-control" %>
	</div>
	<div class="form-group">
		<label>Description</label>
		<%= text_area_tag :description, params[:description], placeholder: "Describe about your pin here...", required: true, class: "form-control" %>
	</div>
	<div class="form-group">
		<label>Upload a image</label>
		<%= file_field_tag :pin, placeholder: "Choose a image file", class: "form-control" %>
	</div>
	<%= submit_tag "Add Pin", class: "btn btn-primary" %>
<% end %>
<br />
<div class="row">
	<h3>My Pins</h3>
	<% @pins.each do |pin| %>
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<%= image_tag pin.pin.url(:medium) %>
				<div class="caption">
					<h3><%= pin.name %></h3>
					<p><%= pin.description[0..50] %></p>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/pins/index.html.erb
<div ng-app="Pin" ng-view>
</div>